"""Render every run folder under docs/ to HTML for GitHub Pages.

Folder layout produced:

    docs/
        index.html                                       ← top-level entry
        .nojekyll                                        ← serve raw, skip Jekyll
        <TICKER>_<DATE>_<MODEL>_<TS>/
            complete_report.md   (kept)
            1_analysts/, ...     (kept)
            index.html           ← rendered from complete_report.md

Pages source: main + /docs. URL: https://<user>.github.io/<repo>/

Run locally:

    python scripts/build_reports_site.py

The script is idempotent — re-running rewrites index.html files but
never touches the markdown.
"""

from __future__ import annotations

import html
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import NamedTuple

try:
    import markdown  # type: ignore
except ImportError:
    markdown = None


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

# Folder name format: <TICKER>_<YYYYMMDD>_<MODEL>_<YYYYMMDD>_<HHMMSS>.
# Older folders may be missing the run timestamp — still accept them and
# fall back to mtime for sort.
RUN_DIR_RE = re.compile(
    r"^(?P<ticker>[A-Za-z0-9.\-]+)_(?P<date>\d{8})_(?P<model>.+?)"
    r"(?:_(?P<run_date>\d{8})_(?P<run_time>\d{6}))?$"
)

PAGE_CSS = """
:root { color-scheme: light dark; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 960px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6;
}
h1, h2, h3 { line-height: 1.3; }
table { border-collapse: collapse; width: 100%; margin: .8rem 0; }
th, td { border: 1px solid rgba(127,127,127,.4); padding: .4rem .6rem; text-align: left; }
code { background: rgba(127,127,127,.15); padding: .1rem .3rem; border-radius: 3px; }
pre { background: rgba(127,127,127,.1); padding: .8rem; overflow-x: auto; border-radius: 6px; }
nav.crumbs { font-size: .9rem; opacity: .8; margin-bottom: 1rem; }
ul.runs { list-style: none; padding: 0; }
ul.runs li { padding: .35rem 0; border-bottom: 1px solid rgba(127,127,127,.2); }
.muted { opacity: .65; font-size: .9rem; }
.disclaimer {
  border-left: 3px solid #d77; background: rgba(215,119,119,.08);
  padding: .6rem 1rem; font-size: .9rem; margin: 1rem 0;
}
"""

DISCLAIMER_HTML = (
  '<div class="disclaimer"><strong>Disclaimer:</strong> Reports below are '
  'generated by an LLM-based research agent for experimentation. They are '
  '<em>not</em> financial advice. Treat the analysis as a synthetic exercise.'
  '</div>'
)


class Run(NamedTuple):
    ticker: str
    analysis_date: str  # YYYY-MM-DD
    model: str
    run_started: str    # YYYY-MM-DD HH:MM:SS
    folder: Path        # docs/<run-folder>


def parse_run_folder(path: Path) -> Run | None:
    if not path.is_dir():
        return None
    m = RUN_DIR_RE.match(path.name)
    if not m:
        return None
    date = m.group("date")
    analysis_date = f"{date[:4]}-{date[4:6]}-{date[6:8]}"
    rd, rt = m.group("run_date"), m.group("run_time")
    if rd and rt:
        run_started = f"{rd[:4]}-{rd[4:6]}-{rd[6:8]} {rt[:2]}:{rt[2:4]}:{rt[4:6]}"
    else:
        run_started = datetime.fromtimestamp(path.stat().st_mtime).strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    return Run(
        ticker=m.group("ticker").upper(),
        analysis_date=analysis_date,
        model=m.group("model"),
        run_started=run_started,
        folder=path,
    )


def render_markdown(text: str) -> str:
    if markdown is not None:
        return markdown.markdown(
            text, extensions=["tables", "fenced_code", "toc"]
        )
    return f"<pre>{html.escape(text)}</pre>"


def page(title: str, body: str, crumbs_html: str = "") -> str:
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n'
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        "<title>" + html.escape(title) + "</title>\n"
        "<style>" + PAGE_CSS + "</style>\n"
        "</head>\n<body>\n"
        + (f'<nav class="crumbs">{crumbs_html}</nav>\n' if crumbs_html else "")
        + DISCLAIMER_HTML + "\n"
        + body
        + "\n</body>\n</html>\n"
    )


def build_run_page(run: Run) -> None:
    body_parts = [
        f"<h1>{html.escape(run.ticker)} — {html.escape(run.analysis_date)}</h1>",
        f"<p class='muted'>Model: <code>{html.escape(run.model)}</code> · "
        f"Run started: {html.escape(run.run_started)}</p>",
    ]
    complete = run.folder / "complete_report.md"
    if complete.is_file():
        body_parts.append(render_markdown(complete.read_text(encoding="utf-8")))
    else:
        body_parts.append("<p><em>complete_report.md missing for this run.</em></p>")

    crumbs = '<a href="../index.html">← All runs</a>'
    (run.folder / "index.html").write_text(
        page(f"{run.ticker} {run.analysis_date}", "\n".join(body_parts), crumbs),
        encoding="utf-8",
    )


def build_top_index(runs: list[Run]) -> None:
    by_ticker: dict[str, list[Run]] = defaultdict(list)
    for r in runs:
        by_ticker[r.ticker].append(r)

    sections = [
        "<h1>TradingAgents Reports</h1>",
        f"<p class='muted'>{len(runs)} runs across {len(by_ticker)} tickers.</p>",
    ]
    for ticker in sorted(by_ticker):
        ticker_runs = sorted(
            by_ticker[ticker],
            key=lambda r: (r.analysis_date, r.run_started),
            reverse=True,
        )
        sections.append(f"<h2 id='{html.escape(ticker)}'>{html.escape(ticker)}</h2>")
        sections.append("<ul class='runs'>")
        for r in ticker_runs:
            sections.append(
                f"<li><a href='{html.escape(r.folder.name)}/index.html'>"
                f"{html.escape(r.analysis_date)}</a> "
                f"· <code>{html.escape(r.model)}</code> "
                f"<span class='muted'>· {html.escape(r.run_started)}</span></li>"
            )
        sections.append("</ul>")

    (DOCS_DIR / "index.html").write_text(
        page("TradingAgents Reports", "\n".join(sections)),
        encoding="utf-8",
    )


def main() -> int:
    if not DOCS_DIR.is_dir():
        print(f"docs/ not found at {DOCS_DIR}", file=sys.stderr)
        return 1

    # Tell GitHub Pages to skip Jekyll and serve raw — our HTML/CSS is
    # self-contained and we don't want Jekyll trying to render the
    # markdown files (which still live alongside for diff visibility).
    (DOCS_DIR / ".nojekyll").touch()

    runs: list[Run] = []
    for child in sorted(DOCS_DIR.iterdir()):
        run = parse_run_folder(child)
        if run is None:
            continue
        build_run_page(run)
        runs.append(run)

    if not runs:
        print("No run folders found under docs/.", file=sys.stderr)
        return 1

    build_top_index(runs)
    print(f"Built {len(runs)} run pages + docs/index.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
