#!/usr/bin/env bash
# Shared default ticker groups for the run_missing_today launchers.

INDEX_TICKERS=(SPY QQQ SOXX XBI)
AI_TICKERS=(NVDA AMD ANET ARM MU INTC AVGO SMCI SNDK MRVL QCOM INTC BE GEV CRDO NBIS LITE COHR AMAT ORCL CARR)
BIG_TICKERS=(CRM MSFT META AAPL GOOGL AMZN TSLA NFLX)
ALPHA_TICKERS=(STRL MKSI KGC LLY UBER TEAM NOW INTU)
CANDIDATES_TICKERS=(TCEHY PDD BABA JD MCD NFLX NKE ADBE TLT UNH NVO)

DEFAULT_TICKERS=(
  "${INDEX_TICKERS[@]}"
  "${AI_TICKERS[@]}"
  "${BIG_TICKERS[@]}"
  "${ALPHA_TICKERS[@]}"
  "${CANDIDATES_TICKERS[@]}"
)
