#!/usr/bin/env bash
# Shared default ticker groups for the run_missing_today launchers.


INDEX_TICKERS=(SPY QQQ SOXX YINN XBI)
AI_TICKERS=(NVDA AMD ANET ARM MU INTC AVGO SMCI SNDK MRVL QCOM INTC BE GEV CRDO NBIS LITE COHR ON AMAT ORCL CARR)
BIG_TICKERS=(CRM MSFT META AAPL GOOGL AMZN TSLA NFLX)
ALPHA_TICKERS=(STRL MKSI CDE HL KGC LLY UBER MELI SE TEAM NOW INTU)
CANDIDATES_TICKERS=(BIDU TCEHY PDD BABA JD MCD NFLX NKE ADBE BILI TLT UNH KHC SNAP POOL AI NVO)
TOPIC_TICKERS=(TXG)

DEFAULT_TICKERS=(
  "${INDEX_TICKERS[@]}"
  "${AI_TICKERS[@]}"
  "${BIG_TICKERS[@]}"
  "${ALPHA_TICKERS[@]}"
  "${CANDIDATES_TICKERS[@]}"
  "${TOPIC_TICKERS[@]}"
)
